### ISSUE TITLE
Add method for monitoring usage

### ISSUE THREAD

**Issue by inaod568** [ScilifelabDataCentre/dds_web#1135]
Our current Safespring contract covers up to 300 TB. 

- [x] 1. Check with Safespring about the status of the usage reports @inaod568: They're still working on it.
- [x] 2. Check with Safespring about what happens when we reach that - if anything @inaod568: According to Safespring there's no technical usage lock, I can increase the quotas easily and whenever I want. 
- [ ] 3. Potentially make a CLI command (and endpoint) for example which monitors the data usage: Info below.

**Comment by inaod568** [comment]
Suggestion by @zishanmirza: Prometheus for monitoring 
Discussed this briefly with @talavis, but was hesitant to set this up on the main cluster since the cluster previously crashed every time stackn started its prometheus instance. 
Therefore looked into checking this either with
- An endpoint only accessible by Super Admin
- Cron job with apscheduler as with the others scheduled tasks
- Flask command within the backend

The endpoint was ruled out after discussion with @talavis, and the flask command would mean that the sys admins would have to run this now and again. That leaves the cron job which would be a good solution, but unfortunately `boto3` used in the backend to connect to Safespring S3 storage does not support checking the available space with a simple command, so instead you have to iterate through all bucket items and get their size. With a huge number of buckets/files and in the future more than the current 3 units, this does not feel feasible and unneccessarily complicated. 

Summary: For now I'm going to rely on getting the usage from Safespring, remind them every Monday, and if there's an issue or I cannot get that info from them for some reason - I can check with s3cmd.
