### ISSUE TITLE
Download through Web

### ISSUE THREAD

**Issue by inaod568** [ScilifelabDataCentre/dds_web#221]
Story 2: As a user I want to be able to get my data in a way that does not require me to be an experienced programmer

- [X] Ability to download via a web interface
- [ ] Change the web interface download setup -- Should NOT use the CLI, should use the functions etc #464
- [ ] Ability to copy-paste a command line from web interface to download using a command line interface #312

**Comment by inaod568** [comment]
Change `must have` -> `should have`  -- see [this comment](https://github.com/ScilifelabDataCentre/dds_web/issues/464#issuecomment-891589960)
