### ISSUE TITLE
Data protection

### ISSUE THREAD

**Issue by inaod568** [ScilifelabDataCentre/dds_web#223]
Story 4: As a user I want my data to be protected from unauthorised parties

- [x] The data should be decrypted after download
- [x] Ability to verify the file integrity
- [ ] Secure handling of encryption keys

**Comment by inaod568** [comment]
Same info as [here](https://github.com/ScilifelabDataCentre/dds_web/issues/231#issuecomment-839580569)
