### ISSUE TITLE
See when uploaded

### ISSUE THREAD

**Issue by inaod568** [ScilifelabDataCentre/dds_web#225]
Story 1: As a user I want to know when the facility has uploaded my data

- [ ] Ability to programmatically (via CLI) see when the facility has uploaded a file
- [ ] Ability to see when the facility has uploaded a file, via the web interface
- [ ] Ability to sign up for notifications for when an upload within a project has been performed
