### ISSUE TITLE
See size

### ISSUE THREAD

**Issue by inaod568** [ScilifelabDataCentre/dds_web#227]
Story 3: As a user I want to know the total size of the data

- [ ] Ability to see the size of each file
- [ ] Ability to see the total size of each project
- [ ] Ability to see the total number of files
