### ISSUE TITLE
Put data

### ISSUE THREAD

**Issue by inaod568** [ScilifelabDataCentre/dds_web#229]
Epic 3: As a facility I want to be able to deliver data to my customers

- [ ] Add option to specify chunk size 
- [ ] Add possibility to exclude file or directory from delivery
- [ ] Add `--no-encryption` option - not all data is sensitive
- [ ] Add `--destination` option

**Comment by inaod568** [comment]
All these are on Jira.
