### ISSUE TITLE
Upload via Web Interface

### ISSUE THREAD

**Issue by inaod568** [ScilifelabDataCentre/dds_web#230]
Story 1: As a facility I want to be able to upload the data in an easy way

- [ ] Ability to upload via web interface
- [ ] Change the web interface upload setup -- Should NOT use the CLI, should use the functions etc #464
- [ ] Check if file exists before upload: #366

**Comment by inaod568** [comment]
Change `must have` -> `should have`  -- see [this comment](https://github.com/ScilifelabDataCentre/dds_web/issues/464#issuecomment-891589960)
