### ISSUE TITLE
Create charging model

### ISSUE THREAD

**Issue by inaod568** [ScilifelabDataCentre/dds_web#414]
User story: As the DDS owner, I want to have a charging model for the units and users.

- [x] Get info from Safespring -- level of granularity, the example files, etc
- [x] Talk to units about their needs
- [ ] Implement system for invoicing

**Comment by inaod568** [comment]
Moving to Jira.
