### ISSUE TITLE
Mid-testing meetings

### ISSUE THREAD

**Issue by inaod568** [ScilifelabDataCentre/dds_web#437]
Points to discuss:
- We can get per facility GBHours from safespring -- do the facilities need per project or more details?
- Invoicing per...? 

- [x] Ancient DNA: Monday 13.00
- [x] HTGE (Bernhard): Tuesday 14.30
- [x] CryoEM (Marta): Wednesday 11.00
- [x] NGI: Thursday 10.00
- [x] ALM (Hjalmar): Thursday 15.00
